version: '3.7'
name: 'gatsby-ss'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - 'data:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - 8000:8000

volumes:
  data:
  node_modules: